version: 2

build:
    os: macOS-12.6.6
    tools:
        python: "3.10"

sphinx:
    configuration: docs/source/conf.py

python:
    install:
        - requirements: docs/requirements.txt
        - requirements: requirements.txt
