---
name: Build & Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - test-ci

defaults:
  run:
    shell: bash

jobs:
  build-test:
    name: Test Run (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Lint and check code formatting
        run: |
          pipx install ruff
          ruff check --output-format=github --target-version=py310
          ruff format --diff --target-version=py310
        continue-on-error: true

      - name: Test dataloaders
        run: >
          pytest --cov=$GITHUB_WORKSPACE --cov-report=xml
          piva/tests/dataloaders_test.py
#          python -m piva.tests.dataloaders_test
#          pytest --cov=$GITHUB_WORKSPACE --cov-report=xml

      - name: Upload coverage to Codecov
        if: >
          ${{ matrix.os == 'ubuntu-latest'
          && matrix.python-version == '3.10' }}
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
