---
name: Pytest unit/integration

on:
  push:
    branches:
      - main
      - test-ci

defaults:
  run:
    shell: bash  # Use bash by default in all jobs

jobs:
  build-test:
    name: Test Run (${ { matrix.python-version } }, ${ { matrix.os } })
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          conda env create --quiet --file environment.yml
#          python -m pip install tox tox-gh-actions

      - name: Run tests
        run: >
          python -m pytest piva/tests/dataloaders_test.py
#          tox -e py${{ matrix.python-version.replace('.', '') }}
#          -- piva/tests/dataloaders_test.py

#      - name: Upload coverage to Codecov
#        if: >
#          ${{ matrix.os == 'ubuntu-latest'
#          && matrix.python-version == '3.10' }}
#        uses: codecov/codecov-action@v3
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
